// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCngoaBoKr7NsoFVKwmIwapnV7Ka_SgI30',
    appId: '1:272620847700:web:a52d727bbf2e66f10063c1',
    messagingSenderId: '272620847700',
    projectId: 'mobile-pro-9cb87',
    authDomain: 'mobile-pro-9cb87.firebaseapp.com',
    storageBucket: 'mobile-pro-9cb87.firebasestorage.app',
    measurementId: 'G-KVD9DRXK57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuBtdlFQ5_FlrPYLkau6KTvOD2zOJ0_48',
    appId: '1:272620847700:android:395466b7c050e6b90063c1',
    messagingSenderId: '272620847700',
    projectId: 'mobile-pro-9cb87',
    storageBucket: 'mobile-pro-9cb87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA2ajSBBht9Uw3QvqgGCgqz95pqbGGPQY',
    appId: '1:272620847700:ios:1348e3ab1b90a3420063c1',
    messagingSenderId: '272620847700',
    projectId: 'mobile-pro-9cb87',
    storageBucket: 'mobile-pro-9cb87.firebasestorage.app',
    iosBundleId: 'com.example.jurnal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA2ajSBBht9Uw3QvqgGCgqz95pqbGGPQY',
    appId: '1:272620847700:ios:1348e3ab1b90a3420063c1',
    messagingSenderId: '272620847700',
    projectId: 'mobile-pro-9cb87',
    storageBucket: 'mobile-pro-9cb87.firebasestorage.app',
    iosBundleId: 'com.example.jurnal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCngoaBoKr7NsoFVKwmIwapnV7Ka_SgI30',
    appId: '1:272620847700:web:6ebbe68f60f7eb9b0063c1',
    messagingSenderId: '272620847700',
    projectId: 'mobile-pro-9cb87',
    authDomain: 'mobile-pro-9cb87.firebaseapp.com',
    storageBucket: 'mobile-pro-9cb87.firebasestorage.app',
    measurementId: 'G-1PHD6QLFGY',
  );
}
